[package]
name = "dll_injection"
version = "0.1.0"
authors = ["IEUser"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = { version = "0.3.8", features = ["memoryapi"] }
clap = "2.33.0"
widestring = "0.4.0"
